development: &development
  developer: true
  base: "http://localhost:3000"
  return_to: "/br/payment"
  email: user@example.com

test:
  <<: *development

production:
  authenticity_token: 55376360B6AB4728B39ABAB13B674C57
  email: contato@desinga.com.br
  return_to: "http://rupy.com.br/br/payment"
